Repository pimcore/web-to-print-bundle, pull requests merged in 2023-05, with the labels that each got.

#21 Move bundle specific css from admin bundle
  doc/02_Print_Documents.md
  public/css/print/print-printermarks.css
Labels: Bug

#14 🔄 synced file(s) with pimcore/sync-common-files
  .github/ci/files/.my.cnf
  .github/ci/files/config/config.yaml
  .github/ci/files/config/packages/security.yaml
  .github/ci/files/config/system.yml
  .github/ci/files/kernel/Kernel.php
Labels: sync

#25 [Task]: Pre-Release TODO
  composer.json
Labels: Task

#27 🔄 synced file(s) with pimcore/sync-common-files
  .gitattributes
  .github/workflows/poeditor-export.yaml
  .github/workflows/static-analysis.yml
Labels: sync

#29 [Settings] Fix 'Unrecognized option' error when saving Chromium processor config
  src/Controller/SettingsController.php
Labels: Bug

#31 Update installation docs and add suggests
  composer.json
  doc/00_Installation.md
Labels: Task
