Repository pimcore/web-to-print-bundle, pull requests merged in 2023-06, with the labels that each got.

#36 Added docs generation action test
  .github/workflows/docs.yaml
Labels: Task

#35 POEditor translations import
  translations/admin.ca.yaml
  translations/admin.de.yaml
  translations/admin.es.yaml
  translations/admin.fr.yaml
  translations/admin.hu.yaml
  translations/admin.it.yaml
  translations/admin.nl.yaml
  translations/admin.pl.yaml
  translations/admin.sk.yaml
  translations/admin.sv.yaml
  translations/admin.th.yaml
  translations/admin.zh_Hans.yaml
Labels: Task, sync

#34 Check all with isset as 0 would evaluate to false
  src/Processor/Gotenberg.php
Labels: Bug
